// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolunteerApp.Infrastructure;

#nullable disable

namespace VolunteerApp.Infrastructure.Migrations
{
    [DbContext(typeof(VolunteerDbContext))]
    [Migration("20260308142139_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VolunteerApp")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.ReviewAggregate.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VolunteerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("VolunteerProfileId");

                    b.HasIndex("AuthorId", "VolunteerId")
                        .IsUnique();

                    b.ToTable("reviews", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.TicketAggregate.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChatRoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descreption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("StudentId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("tickets", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("students", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpokenLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerAchievement", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<int>("TitleDefinitionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("VolunteerId", "TitleDefinitionId");

                    b.HasIndex("TitleDefinitionId");

                    b.ToTable("volunteer_achievments", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Volunteers", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Gamefication.TitleDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CriteriaType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredValue")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceFilterId")
                        .HasColumnType("integer");

                    b.Property<string>("TitlePadge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceFilterId");

                    b.ToTable("title_definitions", "VolunteerApp");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.ReviewAggregate.Review", b =>
                {
                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", null)
                        .WithMany("Reviews")
                        .HasForeignKey("VolunteerProfileId");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.TicketAggregate.Ticket", b =>
                {
                    b.HasOne("VolunteerApp.Domain.Entities.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.StudentProfile", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.StudentProfile", b =>
                {
                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.User", null)
                        .WithOne("StudentProfile")
                        .HasForeignKey("VolunteerApp.Domain.Aggregates.UserAggregate.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerAchievement", b =>
                {
                    b.HasOne("VolunteerApp.Domain.Entities.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("TitleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", null)
                        .WithMany("Achievements")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", b =>
                {
                    b.HasOne("VolunteerApp.Domain.Aggregates.UserAggregate.User", null)
                        .WithOne("VolunteerProfile")
                        .HasForeignKey("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolunteerApp.Domain.Gamefication.TitleDefinition", b =>
                {
                    b.HasOne("VolunteerApp.Domain.Entities.ServiceType", "ServiceFilter")
                        .WithMany()
                        .HasForeignKey("ServiceFilterId");

                    b.Navigation("ServiceFilter");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.User", b =>
                {
                    b.Navigation("StudentProfile");

                    b.Navigation("VolunteerProfile");
                });

            modelBuilder.Entity("VolunteerApp.Domain.Aggregates.UserAggregate.VolunteerProfile", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
